[package]
name = "sorted-iter"
version = "0.1.4"
edition = "2021"

[dependencies]
compare = "0.1.0"
binary-heap-plus = "0.5.0"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
criterion = "0.5"

[[bench]]
name = "multiway_union_binary_heap"
harness = false
test = true
